default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Ert35641106!
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ABCteatro_development

test:
  <<: *default
  database: ABCteatro_test
