default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Ert35641106!
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ABCteatro_development

test:
  <<: *default
  database: ABCteatro_test

production:
  <<: *default
  database: ABCteatro_production
  username: ABCteatro
  password: <%= ENV['ABCTEATRO_DATABASE_PASSWORD'] %>
